import type {DashboardRendition} from './dashboard-service.js';
/** Standalone preview for explicitly supplied renditions; it fetches nothing. */
export function dashboardPreviewHtml(cases:ReadonlyArray<{name:string;rendition:DashboardRendition}>):string {
 const data=JSON.stringify(cases.map(({name,rendition})=>({name,layout:rendition.layout,delay:rendition.frameDelayMs,frames:rendition.frames.map(rgb=>Buffer.from(rgb).toString('base64'))}))).replaceAll('<','\\u003c');
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Agent dashboard pixel previews</title>
<style>body{background:#141820;color:#eee;font:16px system-ui;margin:20px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:24px}section{min-width:0}canvas{image-rendering:pixelated;max-width:100%}canvas[data-scale=enlarged]{width:256px;height:256px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px monospace}h2{font-size:18px}.pixels{display:flex;align-items:start;gap:12px;flex-wrap:wrap}figure{margin:0}figcaption{font-size:13px;color:#bbc}table{border-collapse:collapse;margin:8px 0 20px}th,td{text-align:left;vertical-align:top;padding:3px 10px 3px 0;border-bottom:1px solid #334}</style>
<h1>Agent dashboard pixel previews</h1><p>One session per screen, cycling every ten seconds, attention first. The full label, title, project and every detail stay in the Monitor tab.</p>
<table><tr><th>Area</th><th>Meaning</th></tr>
<tr><td>Tile, top left</td><td>Activity: green ▶ active, blue ‖ idle, red ✕ stopped (interrupted), grey ■ ended, purple ? unknown. The word beside the provider mark repeats it.</td></tr>
<tr><td>Provider mark</td><td>Cyan hollow square: Codex. Orange star: Claude.</td></tr>
<tr><td>Amber chip</td><td>APPROVAL, INPUT or QUESTION. Only then do the tile and chip pulse, as two 500 ms frames. TURN END without a chip is a retained turn-ended notice, never task success.</td></tr>
<tr><td>Label</td><td>The shared label, then title, then session ID, up to 20 characters on two lines; … marks removed characters. A dimmed label with UNSURE means uncertain evidence.</td></tr>
<tr><td>Project</td><td>A dedicated cyan line below the title, up to 15 characters with a middle ellipsis. When present, subagent and uncertainty details sit above the title.</td></tr>
<tr><td>+n SUB</td><td>Active subagents; +9+ means more than nine, ? incomplete evidence.</td></tr>
<tr><td>Bottom strip</td><td>Matching sessions, !attention total, page dots (or page/pages above eight). Right marks: source (filled current, ring stale, ✕ unavailable) and collector (filled running, ‖ quiesced, ✕ faulted, hollow square closed, ? unknown).</td></tr></table>
<p>Each frame is shown at native 64×64 and enlarged 4× with identical RGB pixels. Physical readability and timing are unverified.</p><main></main>
<script>const cases=${data};cases.forEach((item,index)=>{const section=document.createElement('section'),heading=document.createElement('h2'),group=document.createElement('div');heading.textContent=item.name;group.className='pixels';section.append(heading,group);item.frames.forEach((rgb,frame)=>{const figure=document.createElement('figure'),caption=document.createElement('figcaption');caption.textContent=item.frames.length>1?'Frame '+(frame+1)+' of '+item.frames.length+', '+item.delay+' ms':'Single frame';for(const scale of ['native','enlarged']){const canvas=document.createElement('canvas');canvas.width=canvas.height=64;canvas.dataset.index=index;canvas.dataset.frame=frame;canvas.dataset.scale=scale;canvas.setAttribute('aria-label',item.name+' frame '+(frame+1)+' '+scale+' pixel preview');const ctx=canvas.getContext('2d'),pixels=ctx.createImageData(64,64),bytes=atob(rgb);for(let i=0;i<4096;i++){for(let c=0;c<3;c++)pixels.data[i*4+c]=bytes.charCodeAt(i*3+c);pixels.data[i*4+3]=255}ctx.putImageData(pixels,0,0);figure.append(canvas)}figure.append(caption);group.append(figure)});const details=document.createElement('pre');details.textContent=JSON.stringify(item.layout,null,2);section.append(details);document.querySelector('main').append(section)});</script></html>`;
}
