import type {DashboardRendition} from './dashboard-service.js';
/** Standalone preview for explicitly supplied renditions; it fetches nothing. */
export function dashboardPreviewHtml(cases:ReadonlyArray<{name:string;rendition:DashboardRendition}>):string {
 const data=JSON.stringify(cases.map(({name,rendition})=>({name,layout:rendition.layout,rgb:Buffer.from(rendition.rgb).toString('base64')}))).replaceAll('<','\\u003c');
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Agent dashboard pixel previews</title>
<style>body{background:#141820;color:#eee;font:16px system-ui;margin:20px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:24px}section{min-width:0}canvas{image-rendering:pixelated;max-width:100%}canvas[data-scale=enlarged]{width:256px;height:256px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px monospace}h2{font-size:18px}.pixels{display:flex;align-items:start;gap:12px;flex-wrap:wrap}</style>
<h1>Agent dashboard pixel previews</h1><p>S: matching sessions. !: sessions with input, approval or questions. Page/total pages appears at the right.</p>
<p>Rows: C Codex / L Claude; &gt; active, = idle, X interrupted, ] runtime ended, ? unknown; A approval, ! input, ? continuing question; label, or session ID when unlabeled, with … marking removed characters; + active children, ? uncertain; ? stale/uncertain; T retained turn-ended notice.</p>
<p>Footer: F source connection (C current, S stale, ? unavailable); C collector (R running, Q quiesced, F faulted, X closed). Native 64×64 and enlarged 4× show identical RGB pixels. Physical readability and timing are unverified.</p><main></main>
<script>const cases=${data};cases.forEach((item,index)=>{const section=document.createElement('section'),heading=document.createElement('h2'),group=document.createElement('div');heading.textContent=item.name;group.className='pixels';section.append(heading,group);for(const scale of ['native','enlarged']){const canvas=document.createElement('canvas');canvas.width=canvas.height=64;canvas.dataset.index=index;canvas.dataset.scale=scale;canvas.setAttribute('aria-label',item.name+' '+scale+' pixel preview');const ctx=canvas.getContext('2d'),pixels=ctx.createImageData(64,64),bytes=atob(item.rgb);for(let i=0;i<4096;i++){for(let c=0;c<3;c++)pixels.data[i*4+c]=bytes.charCodeAt(i*3+c);pixels.data[i*4+3]=255}ctx.putImageData(pixels,0,0);group.append(canvas)}const details=document.createElement('pre');details.textContent=JSON.stringify(item.layout,null,2);section.append(details);document.querySelector('main').append(section)});</script></html>`;
}
