import {useEffect,useState} from 'react';
import {request,explain,RequestError,type Asset,type Rendition,type Transform} from './api';
import {Preview} from './preview';
export function MediaLibrary({onChoose,active}:{active:boolean;onChoose:(asset:Asset,rendition:Rendition)=>void}){
 const [assets,setAssets]=useState<Asset[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[query,setQuery]=useState('');
 const [selected,setSelected]=useState<{asset:Asset;renditions:Rendition[]}|null>(null),[rendition,setRendition]=useState<Rendition|null>(null);
 const [fit,setFit]=useState<Transform['fit']>('fit'),[scaling,setScaling]=useState<Transform['scaling']>('nearest'),[color,setColor]=useState('#000000');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{let active=true;void request<{items:Asset[];total:number}>(`/assets?offset=${offset}&limit=12&q=${encodeURIComponent(query)}`).then(v=>{if(active){setAssets(v.items);setTotal(v.total);}},e=>{if(active)setError(explain(e));});return()=>{active=false;};},[query,offset,reload]);
 async function run(work:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await work();}catch(e){setError(explain(e));}finally{setBusy(false);}}
 function choose(r:Rendition){setRendition(r);setFit(r.transform.fit);setScaling(r.transform.scaling);setColor('#'+r.transform.background.map(n=>n.toString(16).padStart(2,'0')).join(''));}
 return <section aria-label="Media library">
  <div className="section-head"><div><p className="eyebrow">Your collection</p><h2>Media library</h2></div><label className="upload">Upload media<input aria-label="Upload media" type="file" accept="image/png,image/jpeg,image/gif" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;void run(async()=>{if(file.size>10*1024*1024)throw new RequestError('upload-limit');const data=new FormData();data.append('file',file);const result=await request<{asset:Asset;rendition:Rendition}>('/assets','POST',data);setSelected({asset:result.asset,renditions:[result.rendition]});choose(result.rendition);setReload(n=>n+1);setNotice('Upload complete.');}).catch(()=>{});}}/></label></div>
  <p className="muted">PNG, JPEG or GIF · up to 10 MiB · originals preserved</p>
  {busy&&<p aria-live="polite">Uploading or rendering…</p>}{error&&<p role="alert">{error} <button onClick={()=>setReload(n=>n+1)}>Reload library</button></p>}{notice&&<p aria-live="polite">{notice}</p>}
  <label>Search media<input value={query} maxLength={120} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label>
  <div className="library-layout"><div><div className="asset-grid">{assets.map(asset=><button disabled={busy} className={`asset-card ${selected?.asset.id===asset.id?'selected':''}`} key={asset.id} onClick={()=>void run(async()=>{const detail=await request<{asset:Asset;renditions:Rendition[]}>(`/assets/${asset.id}`);setSelected(detail);if(detail.renditions[0])choose(detail.renditions[0]);})}><span className="file-kind">{asset.source.format.toUpperCase()}</span><strong>{asset.name}</strong><small>{asset.source.width} × {asset.source.height} · {asset.source.frameCount} source frames</small></button>)}</div>
  {!assets.length&&<p className="empty">No matching media. Upload a file to begin.</p>}
  <div className="actions"><button disabled={offset===0||busy} onClick={()=>setOffset(n=>Math.max(0,n-12))}>Previous media</button><span>{total} assets</span><button disabled={offset+12>=total||busy} onClick={()=>setOffset(n=>n+12)}>More media</button></div></div>
  {selected&&rendition&&<aside className="panel"><h3>{selected.asset.name}</h3><Preview key={rendition.id} rendition={rendition} active={active}/>
   <label>Saved rendition<select value={rendition.id} disabled={busy} onChange={e=>{const r=selected.renditions.find(r=>r.id===e.target.value);if(r)choose(r);}}>{selected.renditions.map((r,i)=><option key={r.id} value={r.id}>{i+1}: {r.transform.fit} / {r.transform.scaling}</option>)}</select></label>
   <div className="fields"><label>Fit<select disabled={busy} aria-label="Fit" value={fit} onChange={e=>setFit(e.target.value as Transform['fit'])}><option value="fit">Fit with padding</option><option value="crop">Center crop</option></select></label><label>Scaling<select disabled={busy} aria-label="Scaling" value={scaling} onChange={e=>setScaling(e.target.value as Transform['scaling'])}><option value="nearest">Nearest neighbor</option><option value="smooth">Smooth</option></select></label><label>Padding color<input disabled={busy} type="color" value={color} onChange={e=>setColor(e.target.value)}/></label></div>
   <div className="actions"><button disabled={busy} onClick={()=>void run(async()=>{const background=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16));const result=await request<{rendition:Rendition}>(`/assets/${selected.asset.id}/renditions`,'POST',{transform:{fit,scaling,background}});choose(result.rendition);setSelected({...selected,renditions:[...selected.renditions.filter(r=>r.id!==result.rendition.id),result.rendition]});setNotice('Preview saved.');})}>Render preview</button><button disabled={busy} onClick={()=>onChoose(selected.asset,rendition)}>Use in playlist</button><button className="quiet danger" disabled={busy} onClick={()=>{if(!window.confirm(`Delete ${selected.asset.name}? Referenced media will be preserved.`))return;void run(async()=>{await request(`/assets/${selected.asset.id}`,'DELETE');setSelected(null);setRendition(null);setReload(n=>n+1);});}}>Delete media</button></div>
   <p className="muted">Rendering saves a new preview. Existing playlist items keep their selected rendition.</p>
  </aside>}</div>
 </section>;
}
