import {useEffect,useState} from 'react';
import {request,explain,type Asset,type Rendition,type Playlist,type PlaylistItem} from './api';
type Draft=Omit<PlaylistItem,'id'>&{id?:string;key:string};
export function PlaylistEditor({chosen,onBrowse,onSaved}:{chosen:{asset:Asset;rendition:Rendition}|null;onBrowse:()=>void;onSaved:(playlist:Playlist|null)=>void}){
 const [list,setList]=useState<Playlist[]>([]),[current,setCurrent]=useState<Playlist|null>(null),[items,setItems]=useState<Draft[]>([]),[metadata,setMetadata]=useState<Record<string,Rendition>>({});
 const [name,setName]=useState(''),[newName,setNewName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false);
 async function refresh(){setList(await request<Playlist[]>('/playlists'));}
 useEffect(()=>{void refresh().catch(e=>setError(explain(e)));},[]);
 async function load(p:Playlist){
  const meta={...metadata};
  for(const item of p.items)if(!meta[item.renditionId])meta[item.renditionId]=await request<Rendition>(`/renditions/${item.renditionId}`);
  setMetadata(meta);setCurrent(p);setName(p.name);setItems(p.items.map(item=>({...item,key:item.id})));setDirty(false);onSaved(p);
 }
 async function run(work:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await work();}catch(e){setError(explain(e));}finally{setBusy(false);}}
 async function saved(p:Playlist){setCurrent(p);onSaved(p);await refresh();}
 function edit(index:number,patch:Partial<Draft>){setItems(items.map((item,i)=>i===index?{...item,...patch}:item));setDirty(true);}
 function move(index:number,delta:number){const copy=[...items];[copy[index],copy[index+delta]]=[copy[index+delta]!,copy[index]!];setItems(copy);setDirty(true);}
 function discard(){return !dirty||window.confirm('Discard unsaved item edits?');}
 return <section aria-label="Playlist editor"><div className="section-head"><div><p className="eyebrow">Set the sequence</p><h2>Playlists</h2></div><button className="quiet" disabled={busy} onClick={()=>void run(refresh)}>Refresh playlist list</button></div>
 {error&&<p role="alert">{error}</p>}{notice&&<p aria-live="polite">{notice}</p>}{busy&&<p aria-live="polite">Saving or loading playlist…</p>}
 <div className="editor-layout"><aside className="panel"><form onSubmit={e=>{e.preventDefault();if(!discard())return;void run(async()=>{const p=await request<Playlist>('/playlists','POST',{name:newName});await load(p);setNewName('');await refresh();});}}><label>New playlist name<input required maxLength={120} value={newName} onChange={e=>setNewName(e.target.value)}/></label><button disabled={busy}>Create playlist</button></form>
 <label>Open playlist<select aria-label="Open playlist" disabled={busy} value={current?.id??''} onChange={e=>{const id=e.target.value;if(!id||!discard())return;void run(async()=>load(await request<Playlist>(`/playlists/${id}`)));}}><option value="">Choose a playlist</option>{list.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <h3>Add media</h3>{chosen?<><p>{chosen.asset.name}</p><img className="item-thumb" alt="Selected media" src={`/api/renditions/${chosen.rendition.id}/frames/0.png`}/><button disabled={!current||busy} onClick={()=>{setMetadata({...metadata,[chosen.rendition.id]:chosen.rendition});setItems([...items,{key:crypto.randomUUID(),renditionId:chosen.rendition.id,playback:chosen.rendition.frames.length>1?{mode:'plays',totalPlays:3}:{mode:'duration',durationMs:30000}}]);setDirty(true);}}>Add selected media</button></>:<p className="muted">Choose a rendered preview from the library.</p>}<div className="actions"><button className="quiet" onClick={onBrowse}>Browse media to add</button></div><p className="muted">Add the same media again for an independent timing policy.</p></aside>
 {current?<div><form className="panel" onSubmit={e=>{e.preventDefault();void run(async()=>{const p=await request<Playlist>(`/playlists/${current.id}`,'PATCH',{revision:current.revision,name});await saved(p);setNotice('Name saved.');});}}><label>Playlist name<input aria-label="Playlist name" disabled={busy} required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><div className="actions"><button disabled={busy}>Save name</button><button type="button" disabled={busy} className="quiet" onClick={()=>{const name=window.prompt('Name for duplicate',`${current.name} copy`);if(name)void run(async()=>{await request(`/playlists/${current.id}/duplicate`,'POST',{revision:current.revision,name});await refresh();setNotice('Playlist duplicated from saved items.');});}}>Duplicate playlist</button><button type="button" disabled={busy} className="quiet danger" onClick={()=>{if(window.confirm(`Delete playlist ${current.name}?`))void run(async()=>{await request(`/playlists/${current.id}`,'DELETE',{revision:current.revision});setCurrent(null);setItems([]);setDirty(false);onSaved(null);await refresh();});}}>Delete playlist</button></div>
 <p className="muted">Saved revision {current.revision}. Edits apply to the next session.</p>
 <div className="fields">{(['repeat','shuffle'] as const).map(key=><label className="check" key={key}><input aria-label={key==='repeat'?'Repeat playlist':'Shuffle'} type="checkbox" checked={current[key]} disabled={busy} onChange={e=>void run(async()=>{await saved(await request<Playlist>(`/playlists/${current.id}/options`,'PATCH',{revision:current.revision,[key]:e.target.checked}));})}/>{key==='repeat'?'Repeat playlist':'Shuffle'}</label>)}</div></form>
 <form onSubmit={e=>{e.preventDefault();void run(async()=>{const body=items.map(item=>({...(item.id?{id:item.id}:{}),renditionId:item.renditionId,playback:item.playback}));const p=await request<Playlist>(`/playlists/${current.id}/items`,'PUT',{revision:current.revision,items:body});await load(p);await refresh();setNotice('Playlist items saved.');});}}>
 <ol className="item-list">{items.map((item,index)=>{const animated=(metadata[item.renditionId]?.frames.length??1)>1;return <li className="item-row" key={item.key} aria-label={`Item ${index+1}`}><div className="item-title"><img className="item-thumb" alt={`Item ${index+1} preview`} src={`/api/renditions/${item.renditionId}/frames/0.png`}/><strong>Item {index+1} · {metadata[item.renditionId]?.source.format.toUpperCase()??'Media'}</strong></div><div className="fields">{animated&&<label>Timing mode<select aria-label={`Item ${index+1} timing mode`} disabled={busy} value={item.playback.mode} onChange={e=>edit(index,{playback:e.target.value==='plays'?{mode:'plays',totalPlays:3}:{mode:'duration',durationMs:30000}})}><option value="plays">Total plays</option><option value="duration">Duration</option></select></label>}
 <label>{item.playback.mode==='plays'?'Total plays':'Duration (seconds)'}<input aria-label={`Item ${index+1} ${item.playback.mode==='plays'?'total plays':'seconds'}`} type="number" required min={item.playback.mode==='plays'?1:0.001} step={item.playback.mode==='plays'?1:0.001} max={item.playback.mode==='plays'?Number.MAX_SAFE_INTEGER:Number.MAX_SAFE_INTEGER/1000} value={item.playback.mode==='plays'?item.playback.totalPlays:item.playback.durationMs/1000} disabled={busy} onChange={e=>edit(index,{playback:item.playback.mode==='plays'?{mode:'plays',totalPlays:e.target.valueAsNumber}:{mode:'duration',durationMs:Math.round(e.target.valueAsNumber*1000)}})}/></label></div>
 <div className="actions"><button type="button" className="quiet" aria-label={`Move item ${index+1} up`} disabled={busy||index===0} onClick={()=>move(index,-1)}>Move up</button><button type="button" className="quiet" aria-label={`Move item ${index+1} down`} disabled={busy||index===items.length-1} onClick={()=>move(index,1)}>Move down</button><button type="button" className="quiet danger" aria-label={`Remove item ${index+1}`} disabled={busy} onClick={()=>{setItems(items.filter((_,i)=>i!==index));setDirty(true);}}>Remove</button></div></li>;})}</ol>
 {!items.length&&<p className="empty">No items yet. Choose media from the library.</p>}
 <div className="actions"><button disabled={busy||!dirty}>Save items</button><button type="button" disabled={busy} className="quiet" onClick={()=>{if(discard())void run(async()=>{await load(await request<Playlist>(`/playlists/${current.id}`));setNotice('Saved playlist reloaded.');});}}>Reload saved playlist</button><span className="muted">{dirty?'Unsaved item edits':`${items.length} saved items`}</span></div></form></div>:<p className="empty">Create or open a playlist to start arranging your media.</p>}</div></section>;
}
